# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a57290d09a9f1a58945a8867f60c541be279908be8beb6044b97e4e2ee8d1c97d8d2f1f010252370d11b978a2c5b971f83f6fe3359a79df18569af02295ba9b2

test:
  secret_key_base: 735775fdb415e9e30012dde4c2060432fb70f6e0586e25019d171f6a66976d5ceebfb8592e2b07e78193f106e7203fd7b98b979950d82d7ea36ee4cc38920e95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
